In [3]:
import numpy as np

In [4]:
# Membuat array 1D
mat1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(mat1D)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(mat1D + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [7]:
print(mat2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [12]:
print(mat2D[0] [2])

3


In [10]:
print(mat2D * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [ ]:
print(mat1D.size)
print(mat2D.size)

In [15]:
#Spesial matriks
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size =6)

In [18]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(mOne)

In [ ]:
print(mRandomFloat)

In [ ]:
print(mRandomInt)

In [3]:
x = np.array ([2,6,9])
y = np.array([1,3,5])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)
print(dotProduct)
print(f"Hasil dari dot Product :{dotProduct}")
print(f"Hasil Penjumlahan matriks :{addMatrix}")
print(f"Nilai Minimum dari {x} :{minValue}")
print(f"Nilai maksimum dari {y} : {maxValue}")
print(f"Rata-rata Nilai dari {y} : {meanValue}")
print(f"Nilai median dari {y} : {medianValue}")
print(f"Nilai Deviasi dari {y} : {stdValue}")

NameError: name 'np' is not defined